spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:9000
      client:
        registration:
          autor-ms:
            provider: oauth-server
            client-id: autor-ms
            client-secret: "12345"
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: autor-ms
            scope: openid, profile, read, write
        provider:
          oauth-server:
            issuer-uri: http://127.0.0.1:9000